/* Cue text is a rehearsal aid, kept off the audience view by default. */
(() => {
  const button=document.createElement('button');button.className='cue-toggle';button.textContent='N / Cues';button.setAttribute('aria-expanded','false');
  const panel=document.createElement('aside');panel.className='cue-panel';panel.hidden=true;panel.setAttribute('aria-label','Rehearsal cues');
  document.querySelector('.masthead').insertBefore(button,document.querySelector('#help-open'));document.body.append(panel);
  const fallback={opening:'Introduce the team, recall the 1978 flight and the commercial question, then introduce the CIM argument and the QuietComfort product family.',science:'Explain Young’s interference principle, the water and sound analogies, Lueg’s patent and its electronics limitation, then Bose’s 1978 listening need.',technology:'1:25 / Explain sensing, controller and driver; feedforward/feedback; delay and stability. This is generic ANC engineering.',product:'Follow the timeline from pilots and airline trials to consumer QuietComfort, then explain the QC25 design choices. The battery comparison documents features, not a specific customer complaint or the first integrated-battery model.',conclusion:'Summarise the five points: feedback between capabilities, sponsorship and expertise, usability, customer experience and entrepreneurship.',sources:'References for the team and audience. No spoken source list is needed.'};
  const closingCues={
    'science-11':'Finding: an interference principle needed practical electronics and a listening need before it became headphones. Handoff: technology translates the principle into sensing and control.',
    'technology-8':'Finding: correct timing and stable control are essential. Science ↔ Technology: theory informs prototypes and measurements inform refinement; this is our CIM interpretation. Handoff: integrate the working system with comfort, size and power. Background: early Bose ANC was analogue; Gauger dates digital consumer ANC to QC20 (2013).',
    'product-12':'Finding: acoustic performance, comfort, portability, power and connectivity must work together. Handoff: a usable product still needs customers who recognise the benefit. Market explains that route. The QC1/QC25 battery comparison documents features, not a specific customer complaint or the first integrated battery.'
  };
  fallback['thank-you']='Thank the audience and invite questions. Continue to the sources slide when needed.';
  const update=()=>{const match=location.hash.match(/^#([a-z]+(?:-[a-z]+)*)(?:-(\d+))?$/);const id=match?.[1]||'opening',n=Number(match?.[2]||1)-1;const imported={opening:IntroChapter,science:ScienceChapter,product:ProductChapter,conclusion:ConclusionChapter}[id];const item=imported?null:PresentationContent[id]?.[n];panel.replaceChildren();const h=document.createElement('h3'),p=document.createElement('p'),small=document.createElement('small');h.textContent=imported?.steps[n]?.label||item?.tag||id.toUpperCase();p.textContent=closingCues[`${id}-${n+1}`]||item?.cue||fallback[id]||'';small.textContent='Rehearsal only · N closes cues · R replays this visual · Presenter controls the pace';panel.append(h,p,small);};
  const toggle=()=>{panel.hidden=!panel.hidden;button.setAttribute('aria-expanded',String(!panel.hidden));update();};
  button.addEventListener('click',toggle);
  addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||document.querySelector('dialog[open]')||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key.toLowerCase()==='n'){e.preventDefault();toggle();}if(e.key.toLowerCase()==='r'){const chapter=chapterAt(current);if(chapter){chapter.show(chapterStep);const scene=sectionEls[current].querySelector('.ref-scene:not([hidden])');if(scene){scene.classList.remove('ref-enter');void scene.offsetWidth;scene.classList.add('ref-enter');}}}});
  new MutationObserver(update).observe(document.querySelector('#chapter-label'),{childList:true});update();
})();
